# Generated by Django 4.1 on 2025-02-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-expiry_date'], 'verbose_name': 'Tour Package', 'verbose_name_plural': 'Tour Packages'},
        ),
    ]
